package com.tristarvoid.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF4659A9)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDDE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001356)
val md_theme_light_secondary = Color(0xFF006B5A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF79F8DB)
val md_theme_light_onSecondaryContainer = Color(0xFF00201A)
val md_theme_light_tertiary = Color(0xFF006493)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCAE6FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E30)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE2E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF45464F)
val md_theme_light_outline = Color(0xFF767680)
val md_theme_light_inverseOnSurface = Color(0xFFF3F0F4)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inversePrimary = Color(0xFFB8C3FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4659A9)
val md_theme_light_outlineVariant = Color(0xFFC6C5D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFB8C3FF)
val md_theme_dark_onPrimary = Color(0xFF122878)
val md_theme_dark_primaryContainer = Color(0xFF2D4090)
val md_theme_dark_onPrimaryContainer = Color(0xFFDDE1FF)
val md_theme_dark_secondary = Color(0xFF5ADBC0)
val md_theme_dark_onSecondary = Color(0xFF00382E)
val md_theme_dark_secondaryContainer = Color(0xFF005144)
val md_theme_dark_onSecondaryContainer = Color(0xFF79F8DB)
val md_theme_dark_tertiary = Color(0xFF8CCDFF)
val md_theme_dark_onTertiary = Color(0xFF00344F)
val md_theme_dark_tertiaryContainer = Color(0xFF004B70)
val md_theme_dark_onTertiaryContainer = Color(0xFFCAE6FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE4E1E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE4E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF45464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C5D0)
val md_theme_dark_outline = Color(0xFF90909A)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE4E1E6)
val md_theme_dark_inversePrimary = Color(0xFF4659A9)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB8C3FF)
val md_theme_dark_outlineVariant = Color(0xFF45464F)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF9BACFF)

val NeutralColor = Color(0xFF78909C)
val HappyColor = Color(0xFFFFEE58)
val RomanticColor = Color(0xFFEC407A)
val CalmColor = Color(0xFF42A5F5)
val TenseColor = Color(0xFFFF7043)
val LonelyColor = Color(0xFF8D6E63)
val MysteriousColor = Color(0xFF26A69A)
val AngryColor = Color(0xFFEF5350)
val AwfulColor = Color(0xFF66BB6A)
val SurprisedColor = Color(0xFF29B6F6)
val DepressedColor = Color(0xFFBDBDBD)
val DisappointedColor = Color(0xFFAB47BC)
val ShamefulColor = Color(0xFF7E57C2)
val HumorousColor = Color(0xFFFFCA28)
val SuspiciousColor = Color(0xFFD4E157)
val BoredColor = Color(0xFF26C6DA)

val BackgroundBlack = Color(android.graphics.Color.parseColor("#000000"))
val BackgroundDark = Color(android.graphics.Color.parseColor("#121212"))